### ISSUE TITLE
Can I upgrade the hadoop-core version to 2.6?

### ISSUE THREAD

**Issue by daminggege** [danosipov/sbt-scalding-plugin#1]
Hi Dan,

I found that the default version of hadoop-core in the sbt build file is 1.0.3, not sure if the assembly package will be compatible with my 2.6 environment.

Regards,
Daming

**Comment by danosipov** [comment]
Hadoop dependency is "provided" (not included in the fat JAR), so you can run an assembled JAR on Hadoop 2.6. Please post here if you find any issues.

**Comment by daminggege** [comment]
Cool, many thanks. I'll give it a try.
